/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import React, { useRef, useState, useEffect } from 'react';
import { useFrame } from 'react-three-fiber';
import { useGLTF } from '@react-three/drei/useGLTF';
import { PerspectiveCamera } from '@react-three/drei/PerspectiveCamera';

import { useAnimations } from '@react-three/drei/useAnimations';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/anim.gltf');
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        position={[0.48, -1.41, 0.9]}
        rotation={[0, -0.72, 0]}
        scale={[0.25, 0.25, 0.25]}
      >
        <mesh
          material={materials['Material #2170']}
          geometry={nodes.Sphere002.geometry}
          position={[1.61, -0.13, 0]}
          rotation={[0, 0, 0]}
          scale={[0.93, 0.93, 0.93]}
        />
      </group>
      <group position={[0.48, -1.35, 0.9]} scale={[0.25, 0.25, 0.25]}>
        <group position={[0, -0.08, 0]}>
          <mesh
            material={materials['Material #2148']}
            geometry={nodes.Object005_1.geometry}
          />
          <mesh
            material={materials['16 - Default']}
            geometry={nodes.Object005_2.geometry}
          />
          <mesh
            material={materials['16 - Default']}
            geometry={nodes.Cylinder003.geometry}
            position={[0, -0.08, 0]}
          />
        </group>
        <mesh
          material={materials['Material #2144']}
          geometry={nodes.Object004_1.geometry}
        />
        <mesh
          material={materials['16 - Default']}
          geometry={nodes.Object004_2.geometry}
        />
        <group rotation={[0, 0, 0]}>
          <mesh
            material={materials['Material #2144']}
            geometry={nodes.Object006_1.geometry}
          />
          <mesh
            material={materials['16 - Default']}
            geometry={nodes.Object006_2.geometry}
          />
          <mesh
            material={materials['16 - Default']}
            geometry={nodes.Object006_3.geometry}
          />
        </group>
      </group>
      <group
        position={[0.48, -1.41, 0.9]}
        rotation={[0, -0.72, 0]}
        scale={[0.25, 0.25, 0.25]}
      >
        <mesh
          material={materials['Material #2185']}
          geometry={nodes.Sphere004.geometry}
          position={[0, 0.17, 0]}
          rotation={[2.87, 0, 0]}
          scale={[0.93, 0.93, 0.93]}
        />
      </group>
      <group
        position={[0.48, -1.41, 0.9]}
        rotation={[0, -0.72, 0]}
        scale={[0.25, 0.25, 0.25]}
      >
        <mesh
          name="Sphere005"
          material={materials['Material #2189']}
          geometry={nodes.Sphere005.geometry}
          position={[0, 0.18, 0]}
          rotation={[2.87, 0, 0]}
          scale={[0.93, 0.93, 0.93]}
        />
      </group>
      <pointLight
        intensity={0.4}
        decay={2}
        position={[5.98, 7.45, 1.8]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <pointLight
        intensity={0.2}
        decay={2}
        position={[2.63, 1.85, -0.56]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <pointLight
        intensity={0.2}
        decay={2}
        position={[-1.25, 2.17, -0.98]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <PerspectiveCamera
        makeDefault={false}
        far={10000}
        fov={26.23}
        position={[-0.54, -0.15, 0.99]}
        rotation={[-1.5, -0.63, -1.44]}
      />
      <mesh
        material={materials['16 - Defaultdd']}
        geometry={nodes.Box002.geometry}
        position={[0.48, -1.42, 0.9]}
        rotation={[-2.81, 0.76, 2.91]}
        scale={[0.15, 0.15, 0.15]}
      />
      <group position={[0.48, -1.35, 0.9]} scale={[0.25, 0.25, 0.25]}>
        <mesh
          material={materials['Material #2148']}
          geometry={nodes.Cylinder002_1.geometry}
        />
        <mesh
          material={materials['Material #2148']}
          geometry={nodes.Cylinder002_2.geometry}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/anim.gltf');
